-- =====================================================
-- File: 04_test_execute_cost_allocation.sql
-- Purpose: Test USP_EXECUTECOSTALLOCATION_SF
-- Matches 3-parameter version of the stored procedure
-- Parameters: BUDGETHEADERID, FISCALPERIODID, DRYRUN
-- =====================================================

USE DATABASE PLANNING_DB;
USE SCHEMA PLANNING;

-- =====================================================
-- SETUP: Create test data and allocation rules
-- =====================================================

SELECT '========================================' AS INFO;
SELECT '  SETUP: PREPARE TEST DATA' AS INFO;
SELECT '========================================' AS INFO;

-- Get or create test budget
INSERT INTO BUDGETHEADER (
  BUDGETCODE, BUDGETNAME, BUDGETTYPE, SCENARIOTYPE,
  FISCALYEAR, STARTPERIODID, ENDPERIODID, STATUSCODE, VERSIONNUMBER
)
SELECT
  'BUD_ALLOCATION_TEST',
  'Allocation Test Budget',
  'OPERATIONAL',
  'BASELINE',
  2024,
  (SELECT MIN(FISCALPERIODID) FROM FISCALPERIOD WHERE FISCALYEAR = 2024),  -- STARTPERIODID
  (SELECT MAX(FISCALPERIODID) FROM FISCALPERIOD WHERE FISCALYEAR = 2024),  -- ENDPERIODID
  'APPROVED',
  1
WHERE NOT EXISTS (SELECT 1 FROM BUDGETHEADER WHERE BUDGETCODE = 'BUD_ALLOCATION_TEST');

SET TEST_BUDGET_ID = (SELECT BUDGETHEADERID FROM BUDGETHEADER WHERE BUDGETCODE = 'BUD_ALLOCATION_TEST');

SELECT 'Test Budget ID: ' || $TEST_BUDGET_ID AS INFO;

-- Create test period if not exists
INSERT INTO FISCALPERIOD (
  FISCALYEAR, FISCALQUARTER, FISCALMONTH,
  PERIODNAME, PERIODSTARTDATE, PERIODENDDATE, ISCLOSED
)
SELECT 2024, 1, 1, '2024-01', '2024-01-01', '2024-01-31', FALSE
WHERE NOT EXISTS (SELECT 1 FROM FISCALPERIOD WHERE PERIODNAME = '2024-01');

SET TEST_PERIOD = (SELECT FISCALPERIODID FROM FISCALPERIOD WHERE PERIODNAME = '2024-01');

-- Create test accounts
INSERT INTO GLACCOUNT (ACCOUNTNUMBER, ACCOUNTNAME, ACCOUNTTYPE, ISACTIVE)
SELECT '7000', 'IT Cost Pool', 'EXPENSE', TRUE
WHERE NOT EXISTS (SELECT 1 FROM GLACCOUNT WHERE ACCOUNTNUMBER = '7000');

INSERT INTO GLACCOUNT (ACCOUNTNUMBER, ACCOUNTNAME, ACCOUNTTYPE, ISACTIVE)
SELECT '7100', 'Allocated IT Cost', 'EXPENSE', TRUE
WHERE NOT EXISTS (SELECT 1 FROM GLACCOUNT WHERE ACCOUNTNUMBER = '7100');

-- Create test cost centers
INSERT INTO COSTCENTER (COSTCENTERCODE, COSTCENTERNAME, ISACTIVE, EFFECTIVEFROMDATE)
SELECT 'IT', 'IT Department', TRUE, '2024-01-01'
WHERE NOT EXISTS (SELECT 1 FROM COSTCENTER WHERE COSTCENTERCODE = 'IT');

INSERT INTO COSTCENTER (COSTCENTERCODE, COSTCENTERNAME, ISACTIVE, EFFECTIVEFROMDATE)
SELECT 'SALES', 'Sales Department', TRUE, '2024-01-01'
WHERE NOT EXISTS (SELECT 1 FROM COSTCENTER WHERE COSTCENTERCODE = 'SALES');

INSERT INTO COSTCENTER (COSTCENTERCODE, COSTCENTERNAME, ISACTIVE, EFFECTIVEFROMDATE)
SELECT 'MKTG', 'Marketing Department', TRUE, '2024-01-01'
WHERE NOT EXISTS (SELECT 1 FROM COSTCENTER WHERE COSTCENTERCODE = 'MKTG');

-- Get IDs
SET GL_COST_POOL = (SELECT GLACCOUNTID FROM GLACCOUNT WHERE ACCOUNTNUMBER = '7000');
SET GL_ALLOCATED = (SELECT GLACCOUNTID FROM GLACCOUNT WHERE ACCOUNTNUMBER = '7100');
SET CC_IT = (SELECT COSTCENTERID FROM COSTCENTER WHERE COSTCENTERCODE = 'IT');
SET CC_SALES = (SELECT COSTCENTERID FROM COSTCENTER WHERE COSTCENTERCODE = 'SALES');
SET CC_MKTG = (SELECT COSTCENTERID FROM COSTCENTER WHERE COSTCENTERCODE = 'MKTG');

-- Create test budget line item (IT cost to be allocated)
DELETE FROM BUDGETLINEITEM 
WHERE BUDGETHEADERID = $TEST_BUDGET_ID 
  AND SOURCESYSTEM = 'ALLOCATION_TEST';

INSERT INTO BUDGETLINEITEM (
  BUDGETHEADERID, GLACCOUNTID, COSTCENTERID, FISCALPERIODID,
  ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE,
  SOURCESYSTEM, SOURCEREFERENCE, ISALLOCATED,
  LASTMODIFIEDBYUSERID, LASTMODIFIEDDATETIME
)
VALUES (
  $TEST_BUDGET_ID,
  $GL_COST_POOL,
  $CC_IT,
  $TEST_PERIOD,
  100000,  -- $100,000 IT cost to allocate
  0,
  'MANUAL',
  'ALLOCATION_TEST',
  'TEST_SOURCE',
  FALSE,
  0,
  CURRENT_TIMESTAMP()
);

-- Create allocation tables if not exist
CREATE TABLE IF NOT EXISTS ALLOCATIONRULE (
  ALLOCATIONRULEID NUMBER IDENTITY(1,1) PRIMARY KEY,
  RULECODE STRING NOT NULL,
  RULENAME STRING NOT NULL,
  RULETYPE STRING NOT NULL,
  ALLOCATIONMETHOD STRING NOT NULL,
  TARGETSPECIFICATION VARIANT NOT NULL,
  EFFECTIVEFROMDATE DATE NOT NULL,
  CONSTRAINT UK_ALLOCATIONRULE_CODE UNIQUE (RULECODE)
);

CREATE TABLE IF NOT EXISTS ALLOCATIONRULETARGET (
  ALLOCATIONRULETARGETID NUMBER IDENTITY(1,1) PRIMARY KEY,
  ALLOCATIONRULEID NUMBER,
  TARGETCOSTCENTERID NUMBER,
  TARGETGLACCOUNTID NUMBER,
  TARGETALLOCATIONPCT NUMBER(5,4),
  TARGETISACTIVE BOOLEAN DEFAULT TRUE
);

-- Create allocation rule
INSERT INTO ALLOCATIONRULE (
  RULECODE, RULENAME, RULETYPE, ALLOCATIONMETHOD, 
  TARGETSPECIFICATION, EFFECTIVEFROMDATE
)
SELECT
  'RULE_IT_ALLOC',                    -- RULECODE
  'IT Cost Allocation',               -- RULENAME
  'STANDARD',                         -- RULETYPE
  'PERCENTAGE',                       -- ALLOCATIONMETHOD
  OBJECT_CONSTRUCT(                   -- TARGETSPECIFICATION (VARIANT - required)
    'basis', 'HEADCOUNT',
    'method', 'PERCENTAGE'
  ),
  '2024-01-01'::DATE                  -- EFFECTIVEFROMDATE
WHERE NOT EXISTS (SELECT 1 FROM ALLOCATIONRULE WHERE RULECODE = 'RULE_IT_ALLOC');

SET RULE_ID = (SELECT ALLOCATIONRULEID FROM ALLOCATIONRULE WHERE RULECODE = 'RULE_IT_ALLOC');

-- Create allocation targets
DELETE FROM ALLOCATIONRULETARGET WHERE ALLOCATIONRULEID = $RULE_ID;

INSERT INTO ALLOCATIONRULETARGET (
  ALLOCATIONRULEID, TARGETCOSTCENTERID, TARGETGLACCOUNTID, TARGETALLOCATIONPCT, TARGETISACTIVE
)
VALUES
  ($RULE_ID, $CC_SALES, $GL_ALLOCATED, 0.6000, TRUE),  -- 60% to Sales
  ($RULE_ID, $CC_MKTG, $GL_ALLOCATED, 0.4000, TRUE);   -- 40% to Marketing

-- Create required view
CREATE OR REPLACE VIEW VW_ALLOCATIONRULETARGETS AS
SELECT
  ALLOCATIONRULEID,
  TARGETCOSTCENTERID,
  TARGETGLACCOUNTID,
  TARGETALLOCATIONPCT,
  TARGETISACTIVE
FROM ALLOCATIONRULETARGET
WHERE TARGETISACTIVE = TRUE;

-- Create required function
CREATE OR REPLACE FUNCTION FN_GETALLOCATIONFACTOR(
  SOURCE_CC NUMBER, TARGET_CC NUMBER, BASIS STRING, PERIOD NUMBER, BUDGET NUMBER
)
RETURNS NUMBER
AS $$ 0.5 $$;

SELECT 'Setup Complete' AS STATUS;

-- =====================================================
-- TEST 1: Dry Run Mode
-- =====================================================

SELECT '========================================' AS INFO;
SELECT '  TEST 1: DRY RUN (NO DATA WRITTEN)' AS INFO;
SELECT '========================================' AS INFO;

-- Call procedure with 3 parameters
CALL USP_EXECUTECOSTALLOCATION_SF(
  $TEST_BUDGET_ID,  -- 1. BUDGETHEADERID
  NULL,             -- 2. FISCALPERIODID (NULL = all periods)
  TRUE              -- 3. DRYRUN (don't write data)
);

-- Expected: Returns calculation results without writing to database
-- ROWSALLOCATED should be > 0 but no actual data written

-- Verify no allocated data written
SELECT 
  'Allocated Lines (should be 0 in dry run):' AS INFO,
  COUNT(*) AS COUNT
FROM BUDGETLINEITEM
WHERE BUDGETHEADERID = $TEST_BUDGET_ID
  AND ISALLOCATED = TRUE;

-- =====================================================
-- TEST 2: Actual Allocation
-- =====================================================

SELECT '========================================' AS INFO;
SELECT '  TEST 2: ACTUAL ALLOCATION' AS INFO;
SELECT '========================================' AS INFO;

-- Call procedure in real mode
CALL USP_EXECUTECOSTALLOCATION_SF(
  $TEST_BUDGET_ID,  -- 1. BUDGETHEADERID
  NULL,             -- 2. FISCALPERIODID
  FALSE             -- 3. DRYRUN = FALSE (write data)
);

-- Expected: Data is actually allocated

-- Verify allocated data
SELECT 
  'Allocated Lines:' AS INFO,
  COUNT(*) AS COUNT,
  SUM(bli.ORIGINALAMOUNT) AS TOTAL_ALLOCATED
FROM BUDGETLINEITEM bli
WHERE bli.BUDGETHEADERID = $TEST_BUDGET_ID
  AND bli.ISALLOCATED = TRUE
  AND bli.SOURCESYSTEM = 'COST_ALLOCATION';

-- Show allocation details
SELECT 
  'Allocation Details:' AS INFO,
  cc.COSTCENTERCODE AS TARGET_CC,
  ga.ACCOUNTNUMBER AS TARGET_ACCOUNT,
  bli.ORIGINALAMOUNT AS ALLOCATED_AMOUNT,
  bli.ALLOCATIONPERCENTAGE AS PERCENTAGE
FROM BUDGETLINEITEM bli
LEFT JOIN COSTCENTER cc ON bli.COSTCENTERID = cc.COSTCENTERID
LEFT JOIN GLACCOUNT ga ON bli.GLACCOUNTID = ga.GLACCOUNTID
WHERE bli.BUDGETHEADERID = $TEST_BUDGET_ID
  AND bli.SOURCESYSTEM = 'COST_ALLOCATION'
ORDER BY cc.COSTCENTERCODE;

-- Expected:
-- SALES | 7100 | 60,000 | 0.6000
-- MKTG  | 7100 | 40,000 | 0.4000

-- =====================================================
-- TEST 3: Specific Period Allocation
-- =====================================================

SELECT '========================================' AS INFO;
SELECT '  TEST 3: SPECIFIC PERIOD' AS INFO;
SELECT '========================================' AS INFO;

-- Reset allocation flag
UPDATE BUDGETLINEITEM 
SET ISALLOCATED = FALSE
WHERE BUDGETHEADERID = $TEST_BUDGET_ID
  AND GLACCOUNTID = $GL_COST_POOL;

-- Delete previous allocations
DELETE FROM BUDGETLINEITEM
WHERE BUDGETHEADERID = $TEST_BUDGET_ID
  AND SOURCESYSTEM = 'COST_ALLOCATION';

-- Call for specific period
CALL USP_EXECUTECOSTALLOCATION_SF(
  $TEST_BUDGET_ID,  -- 1. BUDGETHEADERID
  $TEST_PERIOD,     -- 2. Specific period
  FALSE             -- 3. DRYRUN
);

-- Verify only specified period allocated
SELECT 
  'Periods Allocated:' AS INFO,
  fp.PERIODNAME,
  COUNT(*) AS ALLOCATION_COUNT
FROM BUDGETLINEITEM bli
JOIN FISCALPERIOD fp ON bli.FISCALPERIODID = fp.FISCALPERIODID
WHERE bli.BUDGETHEADERID = $TEST_BUDGET_ID
  AND bli.SOURCESYSTEM = 'COST_ALLOCATION'
GROUP BY fp.PERIODNAME;

-- =====================================================
-- TEST 4: Invalid Budget ID
-- =====================================================

SELECT '========================================' AS INFO;
SELECT '  TEST 4: INVALID BUDGET ID' AS INFO;
SELECT '========================================' AS INFO;

CALL USP_EXECUTECOSTALLOCATION_SF(
  99999,  -- 1. Invalid budget ID
  NULL,   -- 2. FISCALPERIODID
  FALSE   -- 3. DRYRUN
);

-- Expected: Error message returned
-- RETURNCODE = -1

-- =====================================================
-- TEST 5: Verify Source Marked as Allocated
-- =====================================================

SELECT '========================================' AS INFO;
SELECT '  TEST 5: VERIFY SOURCE MARKED' AS INFO;
SELECT '========================================' AS INFO;

SELECT 
  'Source IT Cost Status:' AS INFO,
  ISALLOCATED,
  ORIGINALAMOUNT,
  SOURCESYSTEM
FROM BUDGETLINEITEM
WHERE BUDGETHEADERID = $TEST_BUDGET_ID
  AND GLACCOUNTID = $GL_COST_POOL
  AND COSTCENTERID = $CC_IT;

-- Expected: ISALLOCATED = TRUE for source line

-- =====================================================
-- TEST SUMMARY
-- =====================================================

SELECT '========================================' AS INFO;
SELECT '  TEST SUMMARY' AS INFO;
SELECT '========================================' AS INFO;

-- Summary of allocations
SELECT 
  'SUMMARY' AS TYPE,
  COUNT(CASE WHEN ISALLOCATED = FALSE THEN 1 END) AS UNALLOCATED_LINES,
  COUNT(CASE WHEN ISALLOCATED = TRUE AND SOURCESYSTEM = 'ALLOCATION_TEST' THEN 1 END) AS SOURCE_LINES,
  COUNT(CASE WHEN SOURCESYSTEM = 'COST_ALLOCATION' THEN 1 END) AS ALLOCATED_LINES,
  SUM(CASE WHEN SOURCESYSTEM = 'COST_ALLOCATION' THEN ORIGINALAMOUNT ELSE 0 END) AS TOTAL_ALLOCATED_AMOUNT
FROM BUDGETLINEITEM
WHERE BUDGETHEADERID = $TEST_BUDGET_ID;

-- Expected:
-- SOURCE_LINES: 1 (marked as allocated)
-- ALLOCATED_LINES: 2 (Sales + Marketing)
-- TOTAL_ALLOCATED_AMOUNT: 100,000

SELECT '✓ All cost allocation tests completed!' AS STATUS;

-- =====================================================
-- Expected Results Summary:
-- 
-- TEST 1 (Dry Run): ✓ Calculates but doesn't write data
-- TEST 2 (Actual): ✓ Creates 2 allocation lines ($60K + $40K)
-- TEST 3 (Specific Period): ✓ Only allocates for specified period
-- TEST 4 (Invalid Budget): ✓ Returns error gracefully
-- TEST 5 (Source Marked): ✓ Source line marked ISALLOCATED = TRUE
-- =====================================================