
USE DATABASE PLANNING_DB;
USE SCHEMA PLANNING;

-- 创建/重建导入用的 staging 表
CREATE OR REPLACE TABLE BUDGETIMPORT_STAGE (
  ACCOUNTNUMBER     STRING,
  COSTCENTERCODE    STRING,
  FISCALYEAR        NUMBER,
  FISCALMONTH       NUMBER,
  ORIGINALAMOUNT    NUMBER(19,4),
  ADJUSTEDAMOUNT    NUMBER(19,4),
  SPREADMETHODCODE  STRING,
  NOTES             STRING
);