
USE DATABASE PLANNING_DB;
USE SCHEMA PLANNING;

-- Create / recreate the staging table used for bulk budget import
CREATE OR REPLACE TABLE BUDGETIMPORT_STAGE (
  ACCOUNTNUMBER     STRING,
  COSTCENTERCODE    STRING,
  FISCALYEAR        NUMBER,
  FISCALMONTH       NUMBER,
  ORIGINALAMOUNT    NUMBER(19,4),
  ADJUSTEDAMOUNT    NUMBER(19,4),
  SPREADMETHODCODE  STRING,
  NOTES             STRING
);