-- =====================================================
-- File: 02_test_data.sql
-- Purpose: 准备 Bulk Import 的基础主数据和目标预算头
-- =====================================================

USE DATABASE PLANNING_DB;
USE SCHEMA PLANNING;

-- GL Accounts
INSERT INTO GLACCOUNT (ACCOUNTNUMBER, ACCOUNTNAME, ACCOUNTTYPE, ISACTIVE)
SELECT '4000', 'Salaries Account', 'EXPENSE', TRUE
WHERE NOT EXISTS (SELECT 1 FROM GLACCOUNT WHERE ACCOUNTNUMBER = '4000');

INSERT INTO GLACCOUNT (ACCOUNTNUMBER, ACCOUNTNAME, ACCOUNTTYPE, ISACTIVE)
SELECT '5000', 'Travel Account', 'EXPENSE', TRUE
WHERE NOT EXISTS (SELECT 1 FROM GLACCOUNT WHERE ACCOUNTNUMBER = '5000');

-- Cost Centers
INSERT INTO COSTCENTER (
  COSTCENTERCODE, COSTCENTERNAME,
  ISACTIVE, EFFECTIVEFROMDATE
)
SELECT 'CC001', 'Cost Center 001', TRUE, '2024-01-01'
WHERE NOT EXISTS (SELECT 1 FROM COSTCENTER WHERE COSTCENTERCODE = 'CC001');

INSERT INTO COSTCENTER (
  COSTCENTERCODE, COSTCENTERNAME,
  ISACTIVE, EFFECTIVEFROMDATE
)
SELECT 'CC002', 'Cost Center 002', TRUE, '2024-01-01'
WHERE NOT EXISTS (SELECT 1 FROM COSTCENTER WHERE COSTCENTERCODE = 'CC002');

-- Fiscal Periods
INSERT INTO FISCALPERIOD (
  FISCALYEAR, FISCALQUARTER, FISCALMONTH,
  PERIODNAME, PERIODSTARTDATE, PERIODENDDATE, ISCLOSED
)
SELECT 2024, 1, 1, '2024-01', '2024-01-01', '2024-01-31', FALSE
WHERE NOT EXISTS (
  SELECT 1 FROM FISCALPERIOD WHERE FISCALYEAR = 2024 AND FISCALMONTH = 1
);

INSERT INTO FISCALPERIOD (
  FISCALYEAR, FISCALQUARTER, FISCALMONTH,
  PERIODNAME, PERIODSTARTDATE, PERIODENDDATE, ISCLOSED
)
SELECT 2024, 1, 2, '2024-02', '2024-02-01', '2024-02-29', FALSE
WHERE NOT EXISTS (
  SELECT 1 FROM FISCALPERIOD WHERE FISCALYEAR = 2024 AND FISCALMONTH = 2
);

-- Target Budget Header（导入目标预算版本）
INSERT INTO BUDGETHEADER (
  BUDGETCODE, BUDGETNAME, BUDGETTYPE, SCENARIOTYPE,
  FISCALYEAR, STARTPERIODID, ENDPERIODID,
  BASEBUDGETHEADERID, STATUSCODE, VERSIONNUMBER
)
SELECT
  'BUD_IMPORT_TEST',
  'Import Test Budget',
  'OPERATIONAL',
  'BASELINE',
  2024,
  (SELECT FISCALPERIODID FROM FISCALPERIOD WHERE PERIODNAME = '2024-01'),
  (SELECT FISCALPERIODID FROM FISCALPERIOD WHERE PERIODNAME = '2024-01'),
  NULL,
  'DRAFT',
  1
WHERE NOT EXISTS (SELECT 1 FROM BUDGETHEADER WHERE BUDGETCODE = 'BUD_IMPORT_TEST');

-- 保存目标预算头 ID 到会话变量，后续脚本会用到
SET TARGET_BUDGET_ID = (
  SELECT BUDGETHEADERID
  FROM BUDGETHEADER
  WHERE BUDGETCODE = 'BUD_IMPORT_TEST'
);

SELECT 'Setup Complete' AS STATUS;
SELECT 'Target Budget ID: ' || $TARGET_BUDGET_ID AS INFO;