-- =====================================================
-- File: 03_usp_BulkImportBudgetData_SF.sql
-- Purpose: Snowflake 版本的 Bulk Import 存储过程
-- Note: 仅支持从 STAGING_TABLE (BUDGETIMPORT_STAGE) 导入
-- =====================================================

USE DATABASE PLANNING_DB;
USE SCHEMA PLANNING;

CREATE OR REPLACE PROCEDURE USP_BULKIMPORTBUDGETDATA_SF (
  IMPORTSOURCE         STRING,          -- 目前只支持 'STAGING_TABLE'
  STAGINGTABLENAME     STRING,          -- 例如 'BUDGETIMPORT_STAGE'
  TARGETBUDGETHEADERID NUMBER,
  VALIDATIONMODE       STRING DEFAULT 'STRICT',  -- 'STRICT' / 'LENIENT' / 'NONE'
  DUPLICATEHANDLING    STRING DEFAULT 'REJECT'   -- 'REJECT' / 'SKIP'
)
RETURNS NUMBER
LANGUAGE SQL
AS
$$
DECLARE
  STARTTIME    TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
  TOTALROWS    NUMBER := 0;
  VALIDROWS    NUMBER := 0;
  INVALIDROWS  NUMBER := 0;
BEGIN
  --------------------------------------------------------------------
  -- 0. 仅支持 STAGING_TABLE
  --------------------------------------------------------------------
  IF UPPER(:IMPORTSOURCE) <> 'STAGING_TABLE' THEN
    RETURN -1;
  END IF;

  --------------------------------------------------------------------
  -- 1. 把 staging 数据复制到临时表，加上校验字段
  --------------------------------------------------------------------
  CREATE TEMP TABLE IMPORTSTAGING_TEMP AS
  SELECT
    ROW_NUMBER() OVER (ORDER BY 1)      AS ROWID,
    NULL::NUMBER                        AS GLACCOUNTID,
    s.ACCOUNTNUMBER,
    NULL::NUMBER                        AS COSTCENTERID,
    s.COSTCENTERCODE,
    NULL::NUMBER                        AS FISCALPERIODID,
    s.FISCALYEAR,
    s.FISCALMONTH,
    s.ORIGINALAMOUNT,
    s.ADJUSTEDAMOUNT,
    s.SPREADMETHODCODE,
    s.NOTES,
    TRUE::BOOLEAN                       AS ISVALID,
    NULL::STRING                        AS VALIDATIONERRORS
  FROM IDENTIFIER(:STAGINGTABLENAME) s;

  SELECT COUNT(*) INTO :TOTALROWS FROM IMPORTSTAGING_TEMP;

  --------------------------------------------------------------------
  -- 2. 通过代码反查各类 ID
  --------------------------------------------------------------------
  UPDATE IMPORTSTAGING_TEMP stg
  SET GLACCOUNTID = gla.GLACCOUNTID
  FROM GLACCOUNT gla
  WHERE stg.GLACCOUNTID IS NULL
    AND stg.ACCOUNTNUMBER IS NOT NULL
    AND stg.ACCOUNTNUMBER = gla.ACCOUNTNUMBER;

  UPDATE IMPORTSTAGING_TEMP stg
  SET COSTCENTERID = cc.COSTCENTERID
  FROM COSTCENTER cc
  WHERE stg.COSTCENTERID IS NULL
    AND stg.COSTCENTERCODE IS NOT NULL
    AND stg.COSTCENTERCODE = cc.COSTCENTERCODE;

  UPDATE IMPORTSTAGING_TEMP stg
  SET FISCALPERIODID = fp.FISCALPERIODID
  FROM FISCALPERIOD fp
  WHERE stg.FISCALPERIODID IS NULL
    AND stg.FISCALYEAR  = fp.FISCALYEAR
    AND stg.FISCALMONTH = fp.FISCALMONTH;

  --------------------------------------------------------------------
  -- 3. 基础校验
  --------------------------------------------------------------------
  IF UPPER(:VALIDATIONMODE) <> 'NONE' THEN

    UPDATE IMPORTSTAGING_TEMP
    SET ISVALID = FALSE,
        VALIDATIONERRORS = COALESCE(VALIDATIONERRORS || '; ', '') || 'MISSING_ACCOUNT'
    WHERE GLACCOUNTID IS NULL;

    UPDATE IMPORTSTAGING_TEMP
    SET ISVALID = FALSE,
        VALIDATIONERRORS = COALESCE(VALIDATIONERRORS || '; ', '') || 'MISSING_COSTCENTER'
    WHERE COSTCENTERID IS NULL;

    UPDATE IMPORTSTAGING_TEMP
    SET ISVALID = FALSE,
        VALIDATIONERRORS = COALESCE(VALIDATIONERRORS || '; ', '') || 'MISSING_PERIOD'
    WHERE FISCALPERIODID IS NULL;

    UPDATE IMPORTSTAGING_TEMP
    SET ISVALID = FALSE,
        VALIDATIONERRORS = COALESCE(VALIDATIONERRORS || '; ', '') || 'INVALID_AMOUNT'
    WHERE ORIGINALAMOUNT IS NULL;

    -- 期间已关闭
    UPDATE IMPORTSTAGING_TEMP stg
    SET ISVALID = FALSE,
        VALIDATIONERRORS = COALESCE(VALIDATIONERRORS || '; ', '') || 'CLOSED_PERIOD'
    FROM FISCALPERIOD fp
    WHERE stg.FISCALPERIODID = fp.FISCALPERIODID
      AND fp.ISCLOSED = TRUE;

    -- 已存在记录（REJECT 模式下视为错误）
    IF UPPER(:DUPLICATEHANDLING) = 'REJECT' THEN
      UPDATE IMPORTSTAGING_TEMP stg
      SET ISVALID = FALSE,
          VALIDATIONERRORS = COALESCE(VALIDATIONERRORS || '; ', '') || 'ALREADY_EXISTS'
      WHERE EXISTS (
        SELECT 1
        FROM BUDGETLINEITEM bli
        WHERE bli.BUDGETHEADERID = :TARGETBUDGETHEADERID
          AND bli.GLACCOUNTID   = stg.GLACCOUNTID
          AND bli.COSTCENTERID  = stg.COSTCENTERID
          AND bli.FISCALPERIODID= stg.FISCALPERIODID
      );
    END IF;
  END IF;

  SELECT
    SUM(CASE WHEN ISVALID THEN 1 ELSE 0 END),
    SUM(CASE WHEN NOT ISVALID THEN 1 ELSE 0 END)
  INTO :VALIDROWS, :INVALIDROWS
  FROM IMPORTSTAGING_TEMP;

  --------------------------------------------------------------------
  -- 4. 插入有效记录
  --------------------------------------------------------------------
  IF VALIDROWS > 0 THEN
    IF UPPER(:DUPLICATEHANDLING) = 'SKIP' THEN
      INSERT INTO BUDGETLINEITEM (
        BUDGETHEADERID, GLACCOUNTID, COSTCENTERID, FISCALPERIODID,
        ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE,
        SOURCESYSTEM, SOURCEREFERENCE, ISALLOCATED,
        LASTMODIFIEDBYUSERID, LASTMODIFIEDDATETIME
      )
      SELECT
        :TARGETBUDGETHEADERID,
        GLACCOUNTID,
        COSTCENTERID,
        FISCALPERIODID,
        ORIGINALAMOUNT,
        COALESCE(ADJUSTEDAMOUNT, 0),
        SPREADMETHODCODE,
        'BULK_IMPORT',
        'STAGING:' || :STAGINGTABLENAME,
        FALSE,
        0,
        CURRENT_TIMESTAMP()
      FROM IMPORTSTAGING_TEMP stg
      WHERE ISVALID = TRUE
        AND NOT EXISTS (
          SELECT 1 FROM BUDGETLINEITEM bli
          WHERE bli.BUDGETHEADERID = :TARGETBUDGETHEADERID
            AND bli.GLACCOUNTID    = stg.GLACCOUNTID
            AND bli.COSTCENTERID   = stg.COSTCENTERID
            AND bli.FISCALPERIODID = stg.FISCALPERIODID
        );
    ELSE
      INSERT INTO BUDGETLINEITEM (
        BUDGETHEADERID, GLACCOUNTID, COSTCENTERID, FISCALPERIODID,
        ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE,
        SOURCESYSTEM, SOURCEREFERENCE, ISALLOCATED,
        LASTMODIFIEDBYUSERID, LASTMODIFIEDDATETIME
      )
      SELECT
        :TARGETBUDGETHEADERID,
        GLACCOUNTID,
        COSTCENTERID,
        FISCALPERIODID,
        ORIGINALAMOUNT,
        COALESCE(ADJUSTEDAMOUNT, 0),
        SPREADMETHODCODE,
        'BULK_IMPORT',
        'STAGING:' || :STAGINGTABLENAME,
        FALSE,
        0,
        CURRENT_TIMESTAMP()
      FROM IMPORTSTAGING_TEMP
      WHERE ISVALID = TRUE;
    END IF;
  END IF;

  RETURN 0;

EXCEPTION
  WHEN OTHER THEN
    RETURN -1;
END;
$$;