-- =====================================================
-- File: 01_schema_setup.sql
-- Description: Database Schema Setup
-- Purpose: Create database, schema, and tables required for budget consolidation
-- Note: This is a reference script. Actual schema may already exist in your environment.
-- =====================================================

-- =====================================================
-- 1. Database and Schema Setup
-- =====================================================
CREATE DATABASE IF NOT EXISTS PLANNING_DB;
CREATE SCHEMA IF NOT EXISTS PLANNING_DB.PLANNING;
USE DATABASE PLANNING_DB;
USE SCHEMA PLANNING;

-- =====================================================
-- 2. Create Tables (if not exists)
-- =====================================================

-- Fiscal Period Table
CREATE TABLE IF NOT EXISTS FISCALPERIOD (
  FISCALPERIODID       NUMBER IDENTITY(1,1) PRIMARY KEY,
  FISCALYEAR           NUMBER NOT NULL,
  FISCALQUARTER        NUMBER,
  FISCALMONTH          NUMBER,
  PERIODNAME           STRING(20) NOT NULL,
  PERIODSTARTDATE      DATE NOT NULL,
  PERIODENDDATE        DATE NOT NULL,
  ISCLOSED             BOOLEAN DEFAULT FALSE,
  CONSTRAINT UK_FISCALPERIOD_NAME UNIQUE (PERIODNAME)
);

-- Budget Header Table
CREATE TABLE IF NOT EXISTS BUDGETHEADER (
  BUDGETHEADERID       NUMBER IDENTITY(1,1) PRIMARY KEY,
  BUDGETCODE           STRING(50) NOT NULL,
  BUDGETNAME           STRING(200) NOT NULL,
  BUDGETTYPE           STRING(20) NOT NULL, -- OPERATIONAL, CONSOLIDATED, FORECAST, etc.
  SCENARIOTYPE         STRING(20),          -- BASELINE, BEST_CASE, WORST_CASE, etc.
  FISCALYEAR           NUMBER NOT NULL,
  STARTPERIODID        NUMBER,
  ENDPERIODID          NUMBER,
  BASEBUDGETHEADERID   NUMBER,              -- For consolidated budgets, points to source
  STATUSCODE           STRING(20) NOT NULL, -- DRAFT, APPROVED, LOCKED, ARCHIVED
  VERSIONNUMBER        NUMBER DEFAULT 1,
  EXTENDEDPROPERTIES   VARIANT,             -- JSON for additional metadata
  LASTMODIFIEDBYUSERID NUMBER,
  LASTMODIFIEDDATETIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT UK_BUDGETHEADER_CODE UNIQUE (BUDGETCODE),
  CONSTRAINT FK_BUDGETHEADER_BASE FOREIGN KEY (BASEBUDGETHEADERID) REFERENCES BUDGETHEADER(BUDGETHEADERID),
  CONSTRAINT FK_BUDGETHEADER_STARTPERIOD FOREIGN KEY (STARTPERIODID) REFERENCES FISCALPERIOD(FISCALPERIODID),
  CONSTRAINT FK_BUDGETHEADER_ENDPERIOD FOREIGN KEY (ENDPERIODID) REFERENCES FISCALPERIOD(FISCALPERIODID)
);

-- Budget Line Item Table
CREATE TABLE IF NOT EXISTS BUDGETLINEITEM (
  BUDGETLINEITEMID     NUMBER IDENTITY(1,1) PRIMARY KEY,
  BUDGETHEADERID       NUMBER NOT NULL,
  GLACCOUNTID          NUMBER NOT NULL,     -- General Ledger Account
  COSTCENTERID         NUMBER NOT NULL,     -- Cost Center
  FISCALPERIODID       NUMBER NOT NULL,
  ORIGINALAMOUNT       NUMBER(18,2) DEFAULT 0,
  ADJUSTEDAMOUNT       NUMBER(18,2) DEFAULT 0,
  SPREADMETHODCODE     STRING(20),          -- MANUAL, EQUAL, WEIGHTED, etc.
  SOURCESYSTEM         STRING(50),          -- Source of the data
  SOURCEREFERENCE      STRING(100),         -- Reference to source record
  ISALLOCATED          BOOLEAN DEFAULT FALSE,
  ALLOCATIONSOURCELINEID NUMBER,            -- For cost allocation
  ALLOCATIONPERCENTAGE NUMBER(5,4),         -- For cost allocation
  LASTMODIFIEDBYUSERID NUMBER,
  LASTMODIFIEDDATETIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT FK_BUDGETLINEITEM_HEADER FOREIGN KEY (BUDGETHEADERID) REFERENCES BUDGETHEADER(BUDGETHEADERID),
  CONSTRAINT FK_BUDGETLINEITEM_PERIOD FOREIGN KEY (FISCALPERIODID) REFERENCES FISCALPERIOD(FISCALPERIODID)
);

-- Cost Center Table (for hierarchy - optional)
CREATE TABLE IF NOT EXISTS COSTCENTER (
  COSTCENTERID         NUMBER IDENTITY(1,1) PRIMARY KEY,
  COSTCENTERCODE       STRING(20) NOT NULL,
  COSTCENTERNAME       STRING(100) NOT NULL,
  PARENTCOSTCENTERID   NUMBER,              -- For hierarchical structure
  ALLOCATIONWEIGHT     NUMBER(18,10) DEFAULT 1.0,
  ISACTIVE             BOOLEAN DEFAULT TRUE,
  EFFECTIVEFROMDATE    DATE NOT NULL,
  EFFECTIVETODATE      DATE,
  CONSTRAINT UK_COSTCENTER_CODE UNIQUE (COSTCENTERCODE),
  CONSTRAINT FK_COSTCENTER_PARENT FOREIGN KEY (PARENTCOSTCENTERID) REFERENCES COSTCENTER(COSTCENTERID)
);

-- GL Account Table (optional - for reference)
CREATE TABLE IF NOT EXISTS GLACCOUNT (
  GLACCOUNTID          NUMBER IDENTITY(1,1) PRIMARY KEY,
  ACCOUNTNUMBER        STRING(20) NOT NULL,  -- Changed from ACCOUNTCODE to ACCOUNTNUMBER
  ACCOUNTNAME          STRING(100) NOT NULL,
  ACCOUNTTYPE          STRING(20) NOT NULL, -- ASSET, LIABILITY, REVENUE, EXPENSE
  ISACTIVE             BOOLEAN DEFAULT TRUE,
  CONSTRAINT UK_GLACCOUNT_NUMBER UNIQUE (ACCOUNTNUMBER)  -- Changed constraint name
);

-- =====================================================
-- 3. Create Indexes for Performance
-- =====================================================
-- NOTE: Snowflake automatically optimizes queries without manual indexes
-- Manual indexes are only supported on HYBRID TABLES
-- For standard tables, Snowflake's automatic clustering is sufficient


-- =====================================================
-- 4. Verify Schema
-- =====================================================

-- Check table structures
DESC TABLE BUDGETHEADER;
DESC TABLE BUDGETLINEITEM;
DESC TABLE COSTCENTER;
DESC TABLE GLACCOUNT;

SELECT 'Schema setup completed successfully!' AS STATUS;