-- =====================================================
-- File: 02_test_data.sql
-- Description: Test Data for Budget Consolidation
-- Purpose: Insert sample data for testing the stored procedure
-- =====================================================

USE DATABASE PLANNING_DB;
USE SCHEMA PLANNING;

-- =====================================================
-- 1. Insert Fiscal Period
-- =====================================================
INSERT INTO FISCALPERIOD (
  FISCALYEAR, FISCALQUARTER, FISCALMONTH,
  PERIODNAME, PERIODSTARTDATE, PERIODENDDATE,
  ISCLOSED
)
SELECT 2024, 1, 1, '2024-01', '2024-01-01', '2024-01-31', FALSE
WHERE NOT EXISTS (SELECT 1 FROM FISCALPERIOD WHERE PERIODNAME = '2024-01');

-- Get the FISCALPERIODID
SET TEST_PERIOD_ID = (SELECT FISCALPERIODID FROM FISCALPERIOD WHERE PERIODNAME = '2024-01');

-- =====================================================
-- 2. Insert Budget Header (Source Budget)
-- =====================================================
INSERT INTO BUDGETHEADER (
  BUDGETCODE, BUDGETNAME, BUDGETTYPE, SCENARIOTYPE,
  FISCALYEAR, STARTPERIODID, ENDPERIODID,
  BASEBUDGETHEADERID, STATUSCODE, VERSIONNUMBER
)
SELECT
  'BUD_2024_Q1',
  '2024 Q1 Budget',
  'OPERATIONAL',
  'BASELINE',
  2024,
  $TEST_PERIOD_ID,
  $TEST_PERIOD_ID,
  NULL,
  'APPROVED',  -- Must be APPROVED or LOCKED for consolidation
  1
WHERE NOT EXISTS (SELECT 1 FROM BUDGETHEADER WHERE BUDGETCODE = 'BUD_2024_Q1');

-- Get the BUDGETHEADERID
SET SOURCE_BUDGET_ID = (SELECT BUDGETHEADERID FROM BUDGETHEADER WHERE BUDGETCODE = 'BUD_2024_Q1');

-- =====================================================
-- 3. Get or Create GL Accounts and Cost Centers
-- =====================================================

-- Create test GL accounts if they don't exist
INSERT INTO GLACCOUNT (ACCOUNTNUMBER, ACCOUNTNAME, ACCOUNTTYPE, ISACTIVE)
SELECT '1001', 'Salary Expense', 'EXPENSE', TRUE
WHERE NOT EXISTS (SELECT 1 FROM GLACCOUNT WHERE ACCOUNTNUMBER = '1001');

INSERT INTO GLACCOUNT (ACCOUNTNUMBER, ACCOUNTNAME, ACCOUNTTYPE, ISACTIVE)
SELECT '1002', 'Rent Expense', 'EXPENSE', TRUE
WHERE NOT EXISTS (SELECT 1 FROM GLACCOUNT WHERE ACCOUNTNUMBER = '1002');

-- Create test cost centers if they don't exist
INSERT INTO COSTCENTER (COSTCENTERCODE, COSTCENTERNAME, ISACTIVE, EFFECTIVEFROMDATE)
SELECT 'CC_SALES', 'Sales Department', TRUE, '2024-01-01'
WHERE NOT EXISTS (SELECT 1 FROM COSTCENTER WHERE COSTCENTERCODE = 'CC_SALES');

INSERT INTO COSTCENTER (COSTCENTERCODE, COSTCENTERNAME, ISACTIVE, EFFECTIVEFROMDATE)
SELECT 'CC_RND', 'R&D Department', TRUE, '2024-01-01'
WHERE NOT EXISTS (SELECT 1 FROM COSTCENTER WHERE COSTCENTERCODE = 'CC_RND');

-- Get IDs
SET GL_SALARY = (SELECT GLACCOUNTID FROM GLACCOUNT WHERE ACCOUNTNUMBER = '1001');
SET GL_RENT = (SELECT GLACCOUNTID FROM GLACCOUNT WHERE ACCOUNTNUMBER = '1002');
SET CC_SALES = (SELECT COSTCENTERID FROM COSTCENTER WHERE COSTCENTERCODE = 'CC_SALES');
SET CC_RND = (SELECT COSTCENTERID FROM COSTCENTER WHERE COSTCENTERCODE = 'CC_RND');

-- =====================================================
-- 4. Insert Budget Line Items (Test Data)
-- =====================================================

-- Clean existing test data for this budget
DELETE FROM BUDGETLINEITEM WHERE BUDGETHEADERID = $SOURCE_BUDGET_ID;

-- Line Item 1: Salary - Sales Dept - Jan 2024
INSERT INTO BUDGETLINEITEM (
  BUDGETHEADERID, GLACCOUNTID, COSTCENTERID, FISCALPERIODID,
  ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE,
  SOURCESYSTEM, SOURCEREFERENCE, ISALLOCATED,
  LASTMODIFIEDBYUSERID, LASTMODIFIEDDATETIME
)
VALUES (
  $SOURCE_BUDGET_ID,
  $GL_SALARY,
  $CC_SALES,
  $TEST_PERIOD_ID,
  100000, -- ORIGINALAMOUNT
  5000,   -- ADJUSTEDAMOUNT
  'MANUAL',
  'TEST',
  'TEST_DATA_1',
  FALSE,
  1,
  CURRENT_TIMESTAMP()
);

-- Line Item 2: Salary - Sales Dept - Jan 2024 (Another entry, will be consolidated)
INSERT INTO BUDGETLINEITEM (
  BUDGETHEADERID, GLACCOUNTID, COSTCENTERID, FISCALPERIODID,
  ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE,
  SOURCESYSTEM, SOURCEREFERENCE, ISALLOCATED,
  LASTMODIFIEDBYUSERID, LASTMODIFIEDDATETIME
)
VALUES (
  $SOURCE_BUDGET_ID,
  $GL_SALARY,
  $CC_SALES,
  $TEST_PERIOD_ID,
  50000,  -- ORIGINALAMOUNT
  0,      -- ADJUSTEDAMOUNT
  'MANUAL',
  'TEST',
  'TEST_DATA_2',
  FALSE,
  1,
  CURRENT_TIMESTAMP()
);

-- Line Item 3: Salary - R&D Dept - Jan 2024
INSERT INTO BUDGETLINEITEM (
  BUDGETHEADERID, GLACCOUNTID, COSTCENTERID, FISCALPERIODID,
  ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE,
  SOURCESYSTEM, SOURCEREFERENCE, ISALLOCATED,
  LASTMODIFIEDBYUSERID, LASTMODIFIEDDATETIME
)
VALUES (
  $SOURCE_BUDGET_ID,
  $GL_SALARY,
  $CC_RND,
  $TEST_PERIOD_ID,
  200000, -- ORIGINALAMOUNT
  10000,  -- ADJUSTEDAMOUNT
  'MANUAL',
  'TEST',
  'TEST_DATA_3',
  FALSE,
  1,
  CURRENT_TIMESTAMP()
);

-- Line Item 4: Rent - Sales Dept - Jan 2024
INSERT INTO BUDGETLINEITEM (
  BUDGETHEADERID, GLACCOUNTID, COSTCENTERID, FISCALPERIODID,
  ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE,
  SOURCESYSTEM, SOURCEREFERENCE, ISALLOCATED,
  LASTMODIFIEDBYUSERID, LASTMODIFIEDDATETIME
)
VALUES (
  $SOURCE_BUDGET_ID,
  $GL_RENT,
  $CC_SALES,
  $TEST_PERIOD_ID,
  30000,  -- ORIGINALAMOUNT
  0,      -- ADJUSTEDAMOUNT
  'MANUAL',
  'TEST',
  'TEST_DATA_4',
  FALSE,
  1,
  CURRENT_TIMESTAMP()
);

-- =====================================================
-- 5. Verify Test Data
-- =====================================================
SELECT 'Test data inserted successfully!' AS STATUS;
SELECT 'Source Budget ID: ' || $SOURCE_BUDGET_ID AS INFO;

-- Check Budget Header
SELECT 
  BUDGETHEADERID,
  BUDGETCODE,
  BUDGETNAME,
  STATUSCODE,
  FISCALYEAR
FROM BUDGETHEADER 
WHERE BUDGETHEADERID = $SOURCE_BUDGET_ID;

-- Check Budget Line Items (should have 4 rows)
SELECT 
  BUDGETLINEITEMID,
  ga.ACCOUNTNUMBER,
  cc.COSTCENTERCODE,
  fp.PERIODNAME,
  bli.ORIGINALAMOUNT,
  bli.ADJUSTEDAMOUNT,
  bli.ORIGINALAMOUNT + bli.ADJUSTEDAMOUNT AS TOTALAMOUNT
FROM BUDGETLINEITEM bli
LEFT JOIN GLACCOUNT ga ON bli.GLACCOUNTID = ga.GLACCOUNTID
LEFT JOIN COSTCENTER cc ON bli.COSTCENTERID = cc.COSTCENTERID
LEFT JOIN FISCALPERIOD fp ON bli.FISCALPERIODID = fp.FISCALPERIODID
WHERE bli.BUDGETHEADERID = $SOURCE_BUDGET_ID
ORDER BY ga.ACCOUNTNUMBER, cc.COSTCENTERCODE;

SELECT '
Expected consolidation result after running the procedure:
- GL:1001 (Salary), CC:CC_SALES, Period:2024-01 -> $155,000 (100K+5K + 50K+0)
- GL:1001 (Salary), CC:CC_RND,   Period:2024-01 -> $210,000 (200K+10K)
- GL:1002 (Rent),   CC:CC_SALES, Period:2024-01 -> $30,000  (30K+0)
' AS EXPECTED_RESULTS;